In [1]:
#importing the packages
import tensorflow.compat.v1 as tf
tf.compat.v1.disable_eager_execution()
sess= tf.Session()

In [2]:
#Creating a new Graph(not default)
myGraph=tf.Graph()
with myGraph.as_default():
    variable=tf.Variable(30,name='navin')
    initialize=tf.global_variables_initializer()    

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [3]:
#Running computation in session in graph
with tf.Session(graph=myGraph) as sess:
             sess.run(initialize)
             print(sess.run(variable))

30


In [4]:
x = tf.constant(12,dtype= 'float32')
sess= tf.Session()
print(sess.run(x))

12.0


In [5]:
x = tf.constant(12, dtype= 'float32')
with tf.Session() as sess:
    print(sess.run(x))

12.0


In [6]:
x = tf.constant(12, dtype= 'float32') 
y = tf.Variable(x + 11)
model = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(model)
    print(sess.run(y))

23.0


In [7]:
x = tf.constant([14, 23, 40, 30])
y = tf.Variable(x*2 + 100)
model = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(model)
    print(sess.run(y))

[128 146 180 160]


In [8]:
#Placeholder is a variable that we can feed data to at a later time
x = tf.placeholder("float", None)
y = x * 10 + 500
with tf.Session() as sess:
    placeX = sess.run(y, feed_dict={x: [0, 5, 15, 25]})
    print(placeX)

[500. 550. 650. 750.]


In [9]:
x = tf.placeholder("float", [None, 4])
y = x * 10 + 1
with tf.Session() as session:
    dataX = [[12, 2, 0, -2],
              [14, 4, 1, 0],]
    placeX = session.run(y, feed_dict={x: dataX})
    print(placeX)

[[121.  21.   1. -19.]
 [141.  41.  11.   1.]]


In [10]:
x = tf.placeholder("float", [2, 4])
y = x * 10 + 1
with tf.Session() as session:
    dataX = [[12, 2, 0, -2],
              [14, 4, 1, 0],]
    placeX = session.run(y, feed_dict={x: dataX})
    print(placeX)

[[121.  21.   1. -19.]
 [141.  41.  11.   1.]]


In [11]:
x = tf.placeholder("float", [2, 4])
y = x * 10 + 1
with tf.Session() as session:
    dataX = [[12, 2, 0, -2],
              [14, 4, 1, 0],]
    placeX = session.run(y, feed_dict={x: dataX})
    print(placeX)

[[121.  21.   1. -19.]
 [141.  41.  11.   1.]]


In [13]:
#Creating tensor
import numpy as np
image=tf.image.decode_jpeg(tf.read_file('Tiger_1.jpg'))
sess=tf.InteractiveSession()
print(sess.run(tf.shape(image)))

[745 336   3]


C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\client\session.py:1752: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [19]:
print(sess.run(image[10:15,0:4,1]))

[[218 160 119 114]
 [218 160 118 113]
 [220 161 116 110]
 [221 161 116 109]
 [221 162 119 114]]


In [21]:
#Fixed Tensors
sess=tf.Session()
A=tf.zeros([2,3])
print(sess.run(A))

[[0. 0. 0.]
 [0. 0. 0.]]


In [22]:
#Declare another variable
B=tf.ones([4,3])
print(sess.run(B))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [23]:
C=tf.fill([2,3],13)
print(sess.run(C))

[[13 13 13]
 [13 13 13]]


In [24]:
D=tf.diag([4,-3,2])
print(sess.run(D))

[[ 4  0  0]
 [ 0 -3  0]
 [ 0  0  2]]


In [25]:
E=tf.constant([4,2,3,1])
print(sess.run(E))

[4 2 3 1]


In [28]:
#Sequence tensor

In [26]:
G=tf.range(start=6,limit=45,delta=3)
print(sess.run(G))

[ 6  9 12 15 18 21 24 27 30 33 36 39 42]


In [27]:
H=tf.linspace(10.0,92.0,5) #creates sequence of evenly spaced value
print(sess.run(H))

[10.  30.5 51.  71.5 92. ]


In [31]:
#Random Tensor

In [28]:
R1=tf.random_uniform([2,3],minval=0,maxval=4)
print(sess.run(R1))

[[2.5541296  1.5269313  1.540369  ]
 [0.94328165 0.47364473 2.9980817 ]]


In [33]:
R2=tf.random_normal([2,3],mean=5,stddev=4)
print(sess.run(R2))

[[ 4.92087889  7.51223087  9.2412281 ]
 [ 6.65636778  0.94417238  8.15496731]]


In [29]:
R3=tf.random_shuffle(tf.diag([3,-2,4]))
print(sess.run(R3))

[[ 0 -2  0]
 [ 0  0  4]
 [ 3  0  0]]


In [30]:
R4=tf.random_crop(tf.diag([3,-2,4]),[3,2])
print(sess.run(R4))

[[ 3  0]
 [ 0 -2]
 [ 0  0]]


In [31]:
print(sess.run(tf.diag([3,-2,4])))

[[ 3  0  0]
 [ 0 -2  0]
 [ 0  0  4]]


In [32]:
print(sess.run(tf.zeros([2,4])))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [33]:
print(sess.run(tf.diag([3,1,5,-2])))

[[ 3  0  0  0]
 [ 0  1  0  0]
 [ 0  0  5  0]
 [ 0  0  0 -2]]


In [37]:
print(sess.run(tf.range(start=4, limit=16, delta=2)))

[ 4  6  8 10 12 14]


In [40]:
#12

In [41]:
#Working with matrices

In [39]:
import tensorflow.compat.v1 as tf
import numpy as np
sess=tf.Session()
A=tf.random_uniform([3,2])
B=tf.fill([2,4],3.5)
C=tf.random_uniform([3,4])

In [40]:
print(sess.run(A))

[[0.46633458 0.9366181 ]
 [0.04441679 0.42088854]
 [0.53994775 0.8757559 ]]


In [41]:
print(sess.run(B))

[[3.5 3.5 3.5 3.5]
 [3.5 3.5 3.5 3.5]]


In [42]:
print(sess.run(tf.matmul(A,B)))    # Matrix multiplication

[[3.0879946 3.0879946 3.0879946 3.0879946]
 [4.287131  4.287131  4.287131  4.287131 ]
 [1.4951131 1.4951131 1.4951131 1.4951131]]


In [43]:
print(sess.run(tf.matmul(A,B)+C))    #Multiplication and addition

[[6.134966  5.951398  6.2283883 5.9512043]
 [2.2659597 2.4756415 2.9510677 3.1385527]
 [3.6609702 3.6437068 3.9271376 3.305163 ]]


In [47]:
#Activation function

In [44]:
#working on tanh function
E=tf.nn.tanh([10,2,0.5,-0.5,-1.0,-2,-10.0])
print(sess.run(E))

[ 1.          0.9640276   0.46211717 -0.46211717 -0.7615942  -0.9640276
 -1.        ]


In [45]:
#sigmoid function
J=tf.nn.sigmoid([10,2,0.5,-0.5,-1.0,-2,-10.0])
print(sess.run(J))

[9.9995458e-01 8.8079703e-01 6.2245935e-01 3.7754068e-01 2.6894143e-01
 1.1920292e-01 4.5397872e-05]


In [46]:
sess=tf.Session()
print(sess.run(tf.constant([-2,1,-3,13])))
print('\n\n')
A=tf.nn.relu([-2,1,-3,13])
print(sess.run(A))

[-2  1 -3 13]



[ 0  1  0 13]


In [47]:
sess=tf.Session()
print(sess.run(tf.constant([-2,1,-3,13])))
print('\n\n')
A=tf.nn.relu6([-2,1,-3,13])
print(sess.run(A))

[-2  1 -3 13]



[0 1 0 6]


In [48]:
sess=tf.Session()
print(sess.run(tf.constant([[-2,1,-3],[10,-16,-5]])))
print('\n')
C=tf.nn.relu([[-2,1,-3],[10,-16,-5]])
print(sess.run(C))

[[ -2   1  -3]
 [ 10 -16  -5]]


[[ 0  1  0]
 [10  0  0]]


In [49]:
#Relu function
Re=tf.nn.relu([-2,1,-3,13])
print(sess.run(Re))

[ 0  1  0 13]


In [54]:
#elu function
H=tf.nn.elu([10,2,1,0.5,0,-0.5,-1.,-2.,-10.])
print(sess.run(H))

[ 10.           2.           1.           0.5          0.          -0.39346933
  -0.63212055  -0.86466473  -0.99995458]


In [55]:
#Relu6 function
Re6=tf.nn.relu6([10,2,1,0.5,0,-0.5,-1.,-2.,-10.])
print(sess.run(Re6))

[ 6.   2.   1.   0.5  0.   0.   0.   0.   0. ]


In [56]:
#softmax function
X=tf.nn.softmax([10,2,0.5,0,-0.5,-1.0,-2,-10.0])
print(sess.run(X))

[  9.99494076e-01   3.35292920e-04   7.48139573e-05   4.53769608e-05
   2.75225175e-05   1.66932514e-05   6.14110377e-06   2.06011097e-09]


In [57]:
#softsign function
Y=tf.nn.softsign([10,2,0.5,0,-0.5,-1.0,-2,-10.0])
print(sess.run(Y))

[ 0.90909094  0.66666669  0.33333334  0.         -0.33333334 -0.5
 -0.66666669 -0.90909094]


In [58]:
#softplus function
Z=tf.nn.softplus([10,2,0.5,0,-0.5,-1.0,-2,-10.0])
print(sess.run(Z))

[  1.00000458e+01   2.12692809e+00   9.74076986e-01   6.93147182e-01
   4.74076986e-01   3.13261628e-01   1.26928046e-01   4.54177061e-05]


In [59]:
import numpy as np
sess=tf.Session()

In [56]:
#Assuming prediction model
pred=np.asarray([0.2,0.3,0.5,10.0,12.0,13.0,3.5,7.4,3.9,2.3])
#convert ndarray into tensor
x_val=tf.convert_to_tensor(pred)
#Assuming actual values
actual=np.asarray([0.1,0.4,0.6,9.0,11.0,12.0,3.4,7.1,3.8,2.0])

In [57]:
#L2 loss:L1=(pred-actual)^2
l2=tf.square(pred-actual)
l2_out=sess.run(tf.round(l2))
print(l2_out)

[0. 0. 0. 1. 1. 1. 0. 0. 0. 0.]


In [58]:
#L2 loss:L1=abs(pred-actual)
l1=tf.abs(pred-actual)
l1_out=sess.run(l1)
print(l1_out)

[0.1 0.1 0.1 1.  1.  1.  0.1 0.3 0.1 0.3]


In [59]:
#cross entropy loss
softmax_xentropy_variable=tf.nn.sigmoid_cross_entropy_with_logits(logits=l1_out,labels=l2_out)
print(sess.run(softmax_xentropy_variable))

[0.74439666 0.74439666 0.74439666 0.31326169 0.31326169 0.31326169
 0.74439666 0.85435524 0.74439666 0.85435524]


In [51]:
#Optimization

In [52]:
x = tf.Variable(3, name='x', dtype=tf.float32)
log_x = tf.log(x)
log_x_squared = tf.square(log_x)

In [53]:
optimizer = tf.train.GradientDescentOptimizer(0.7)
train = optimizer.minimize(log_x_squared)

In [54]:
init =tf.global_variables_initializer()

In [55]:
#Finally running computation
with tf.Session() as session:
    session.run(init)
    print("starting at", "x:", session.run(x), "log(x)^2:", session.run(log_x_squared))
    for step in range(10):  
      session.run(train)
      print("step", step, "x:", session.run(x), "log(x)^2:", session.run(log_x_squared))    



starting at x: 3.0 log(x)^2: 1.206949
step 0 x: 2.4873142 log(x)^2: 0.8302918
step 1 x: 1.9744377 log(x)^2: 0.46278587
step 2 x: 1.492074 log(x)^2: 0.16013372
step 3 x: 1.1166008 log(x)^2: 0.01216367
step 4 x: 0.97831976 log(x)^2: 0.00048042962
step 5 x: 1.009686 log(x)^2: 9.2917726e-05
step 6 x: 0.9963203 log(x)^2: 1.3590131e-05
step 7 x: 1.0015005 log(x)^2: 2.2480888e-06
step 8 x: 0.99940455 log(x)^2: 3.5477242e-07
step 9 x: 1.0002389 log(x)^2: 5.7057385e-08


In [60]:
# placeholders declaration
x=tf. placeholder(tf.int32, [5])
y=tf. placeholder(tf.int32, [5])

In [61]:
# Metrices declaration
acc, acc_op=tf.metrics.accuracy(labels=x, predictions=y)

In [62]:
#session initialization
sess=tf.InteractiveSession()
sess.run(tf.global_variables_initializer())
sess.run(tf.local_variables_initializer())

In [63]:
#value assign
val= sess.run([acc,acc_op], feed_dict={x: [1,1,0,1,0], y: [0,1,0,0,1]})

In [64]:
#print Accuracy
val_acc=sess.run(acc)
print(val_acc)

0.4
