In [11]:
import tensorflow.compat.v1 as tf
tf.compat.v1.disable_eager_execution()
a = tf.constant(5.0)
b = tf.constant(6.0)
c = a * b
print(c)

# Launch the graph in a session.
sess = tf.compat.v1.Session()

# Evaluate the tensor `c`.
print(sess.run(c)) # prints 30.0

Tensor("mul_2:0", shape=(), dtype=float32)
30.0


In [12]:
x = tf.constant(12,dtype= 'float32')
sess= tf.Session()
print(sess.run(x))

12.0


In [13]:
x = tf.constant(12, dtype= 'float32') 
y = tf.Variable(x + 11)
model = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(model)
    print(sess.run(y))

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
23.0


In [14]:
x = tf.constant([14, 23, 40, 30])
y = tf.Variable(x*2 + 100)
model = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(model)
    print(sess.run(y))

[128 146 180 160]


In [15]:
#Placeholder is a variable that we can feed data to at a later time
x = tf.placeholder("float", None)
y = x * 10 + 500
with tf.Session() as sess:
    placeX = sess.run(y, feed_dict={x: [0, 5, 15, 25]})
    print(placeX)

[500. 550. 650. 750.]


In [16]:
x = tf.placeholder("float", [None, 4])
y = x * 10 + 1
with tf.Session() as session:
    dataX = [[12, 2, 0, -2],
              [14, 4, 1, 0],]
    placeX = session.run(y, feed_dict={x: dataX})
    print(placeX)

[[121.  21.   1. -19.]
 [141.  41.  11.   1.]]


In [17]:
x = tf.placeholder("float", [2, 4])
y = x * 10 + 1
with tf.Session() as session:
    dataX = [[12, 2, 0, -2],
              [14, 4, 1, 0],]
    placeX = session.run(y, feed_dict={x: dataX})
    print(placeX)

[[121.  21.   1. -19.]
 [141.  41.  11.   1.]]


In [19]:
# Weight and Bias as Variables as they are to be tuned
W = tf.Variable([2], dtype=tf.float32) 
b = tf.Variable([3], dtype=tf.float32)
# Training dataset that will be fed while training
x = tf.placeholder(tf.float32)
# Linear Model
linear_model = W * x + b
